### ISSUE TITLE
EPIC: 2.0 code re-write 

### ISSUE THREAD

**Issue by codelastnight** [codelastnight/to-path-figma#42]
# im finally fixing this plugin for good (aptly named project cross my fingers & hope)
I first wrote this plugin when I was a freshman in college. It was my first react project and I also didn't know linear algebra at the time💀 dependencies are extremely out of date, overly complex IPC. The core algorithm i wrote to calculate angles is really bad and slow, etc etc. its perfect 💯(it desperately needs a rewrite) + I'm basically a pro at matrices now (I got a B- in class) so this should be pretty easy to fix everything (I will run into 9000 issues)  

### TODO:
- [x] update to a newer code pipeline (add pnpm, tailwind, latest dependancies, etc)
- [x] update and take advantage of new figma api
- [x] rethink UX to address many comments who didn't realize they could update after applying.
- [x] design new UI
- [ ] apply new UI in svelte
- [x] rethink text implementation. need a better way to figure out kerning.
- [ ] implement new text parsing and applying.
- [x] fix matrix implementation (rotation, translation, etc)
- [ ] test & optimize code

track this on the 2.0 branch
